### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by ethereal-sandeep** [JonathanBennett/prerender-redis-cache#15]
Hi,

I have integrated this with latest prerender google chrome version but getting this error continuously.
I have set the REDIS_URL like below:

export `REDIS_URL=redis://"":""@redis-server-here:6379/0`

**NPM versions:**
{ 
  npm: '3.10.10',
  node: '6.11.5'
 }

**ERROR**
`SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Command.callback (/home/ec2-user/prerender/node_modules/prerender-redis-cache/lib/prerenderRedisCache.js:72:37)
    at normal_reply (/home/ec2-user/prerender/node_modules/redis/index.js:726:21)
    at RedisClient.return_reply (/home/ec2-user/prerender/node_modules/redis/index.js:824:9)
    at JavascriptRedisParser.returnReply (/home/ec2-user/prerender/node_modules/redis/index.js:192:18)
    at JavascriptRedisParser.execute (/home/ec2-user/prerender/node_modules/redis-parser/lib/parser.js:574:12)
    at Socket.<anonymous> (/home/ec2-user/prerender/node_modules/redis/index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)`

Kindly help

**Comment by thoop** [comment]
Does your redis server have HTML cached under those URLs already? Can you clear your redis cache and try again? It seems like redis is returning HTML instead of the JSON object that is expected.

**Comment by ethereal-sandeep** [comment]
Yes i tried clearing cache and re run the curl but doesn't seems to be working. still getting this error 

`unable to load URL TypeError: Page.addScriptToEvaluateOnNewDocument is not a function  at Page.enable.then (/home/ec2-user/prerender/lib/browsers/chrome.js:414:9)`

**Comment by thoop** [comment]
Which version of Chrome and which version of Prerender are you running? That seems different from this redis cache repo so you might want to make an issue on https://github.com/prerender/prerender for that.

**Comment by ethereal-sandeep** [comment]
chrome-remote-interface@~0.25.7 & prerender "version": "5.4.4". I have created an issue [here](https://github.com/prerender/prerender/issues/534)

**Comment by JonathanBennett** [comment]
Closing as this doesn't seem related to the caching plugin.
