### ISSUE TITLE
TypeError: undefined is not a function in RedisClient 

### ISSUE THREAD

**Issue by aalin** [JonathanBennett/prerender-redis-cache#3]
Not sure which command it's trying to send, but possibly ping. https://github.com/JonathanBennett/prerender-redis-cache/commit/324cad652ca48a0b60d257a61daea6320597d144 seemed to fix my issues at first, but then I got this:

```
prerender_1 | 2015-03-30T21:06:29.901Z started phantom
prerender_1 | /app/node_modules/prerender-redis-cache/node_modules/redis/index.js:959
prerender_1 |             return this.send_command(command, to_array(arguments));
prerender_1 |                         ^
prerender_1 | TypeError: undefined is not a function
prerender_1 |     at RedisClient.(anonymous function) (/app/node_modules/prerender-redis-    cache/node_modules/redis/index.js:959:25)
prerender_1 |     at wrapper [as _onTimeout] (timers.js:265:14)
prerender_1 |     at Timer.listOnTimeout (timers.js:110:15)
prerender_1 | 2015-03-30T21:09:30.206Z starting worker thread #0
```

I don't have time to investigate at the moment, so I'm opening this issue.

**Comment by JonathanBennett** [comment]
Hey @aalin - Thanks for your commits. For the time being I'm going to rollback but keep this open as I liked the ping fix for the disconnect to keep connection alive. Just don't want people pulling a broken package from NPM. J
